export const DEFAULT_REVIEWED_BUNDLE = {
  packageId: "default-reviewed-bundle",
  displayName: "Default Reviewed Bundle",
  version: "0.1.0",
  digest: "sha256:0f5f8ef9566a58824e7f6008b2f047a4181d4be90a58f66aabe973b083e100b6",
  workflowDigest: "sha256:1949c691df27c44afc5818e88b0ce245b7c8de9e70583d1eff1a1d560f6a8f35",
  artifactId: "run-reviewed-bundle:candidate-1",
  artifactType: "stub_artifact",
  artifactTitle: "Reviewed stub artifact",
  artifactSummary: "A deterministic stub artifact from the reviewed bundle.",
  artifactBodyText: "The reviewed bundle should emit one grounded stub artifact.",
  disclosure: {
    userCopy: "Reads bounded Listen excerpts and emits a single reviewed stub artifact.",
    credentialOwner: "none" as const,
    providerClass: "none" as const,
    egressClass: "none" as const,
  },
  runtime: {
    runtimeClass: "stub" as const,
    providerClass: "none" as const,
    credentialMode: "none" as const,
    egressClass: "none" as const,
    maxModelCalls: 0,
    allowedTools: [] as string[],
    disallowedTools: ["tinycloud", "shell", "network"] as string[],
  },
  limits: {
    maxSourceRefs: 1,
    maxInputTokens: 12000,
    maxOutputBytes: 4096,
    timeoutMs: 1000,
  },
  stageCapabilities: [] as Array<{ stageId: string; capabilities: string[]; authority: "none"; egressClass: "none"; spendClass: "none" }>,
  sourceRef: {
    sourceRefId: "src-default",
    sourceKind: "listen_conversation" as const,
    sourceId: "conversation-default",
    observedPath: "sql_transcript_text",
    observedHash: "sha256:feed-default-source",
    observedAt: "2026-07-02T00:00:00.000Z",
    quoteLineRefs: ["0"],
  },
} as const;

